
name: Tweet Screenshot Daily

on:
  schedule:
    - cron: '0 9 * * *'  # Runs daily at 9 AM UTC
  workflow_dispatch:

jobs:
  snapshot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Puppeteer dependencies
        run: npm install puppeteer node-fetch

      - name: Run screenshot script
        run: node scripts/screenshot_tweets.js

      - name: Commit and push screenshots
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add screenshots/
          git commit -m "📸 Daily tweet screenshots"
          git push
        continue-on-error: true
